### PR TITLE
fix: Harden the rate-limiter data-race regression test so it cannot s…

### LINKED ISSUE #2958: Harden the rate-limiter data-race regression test so it cannot silently no-op
### Task Description

`TestRateLimiterMemoryStore_ConcurrentAllowAndIncreaseTimeout` in `internal/server/session_failures_storage_test.go` (added in #2881) guards the fix for #2879, but it can pass while exercising nothing.

`IncreaseTimeout` returns silently when the identifier has no visitor yet, and the visitor is only created by the first `Allow`:

```go
func (store *RateLimiterMemoryStore) IncreaseTimeout(identifier string) {
	store.mutex.Lock()
	limiter, exists := store.visitors[identifier]
	if exists {
		limiter.timeout *= 2
	}
	store.mutex.Unlock()
}
```

Nothing in the test orders the two goroutines, so a scheduling in which the writer goroutine drains all 200 iterations before the first `Allow` lands makes every one of its calls a no-op. The test has no assertions at all, so that run reports green having touched `Visitor.timeout` exactly once.

Two changes fix it:

1. Create the visitor with a single `Allow` call before the goroutines start, so every `IncreaseTimeout` iteration actually writes the field.
2. Assert the outcome. Once the visitor exists up front the result is deterministic — the `Allow` goroutine never writes `timeout`, so the final value is exactly `initialTimeout << iterations`. `iterations` needs to come down from 200 for that (`20ms << 200` overflows `time.Duration`); 20 doublings is still ample overlap for the race detector.

Use `testify` for the assertions, per the repo convention.

This is test-only — no change to `internal/server/session_failures_storage.go` is needed. The race fix from #2881 is complete and the throttle behaves correctly today; the defect is purely that its regression guard can under-exercise itself.

### Reasoning / Benefit

This is the regression guard for a data race in the login brute-force throttle, so it is the only thing standing between a future refactor of `Allow` and silently reintroducing #2879. A guard that can pass without exercising the code path it guards is worse than no guard, because it reads as coverage.

The assertion is the more valuable half: today the test verifies nothing about behaviour and would pass unchanged if `IncreaseTimeout` stopped doubling altogether. `RateLimiterMemoryStore` has an injectable `timeNow` seam and no behavioural tests at all — this is the natural place to start using it.

### Additional Context

- Introduced by #2881, which fixed #2879.
- Test: [`internal/server/session_failures_storage_test.go`](https://github.com/openeverest/openeverest/blob/main/internal/server/session_failures_storage_test.go)
- Code under test: [`internal/server/session_failures_storage.go`](https://github.com/openeverest/openeverest/blob/main/internal/server/session_failures_storage.go)
- **Affects both branches.** The test file is byte-identical on `main` and `release-2.0`, so the change needs to land on both.
- `make test` runs `go test -race`, so the detector half of the test does run in CI — the gap is purely that it can end up with nothing to detect.

### PR DESCRIPTION
**Pull request by Phran6ix**
- Added a `store.Allow()` to create a new visitor map.
- Added an `assert` to compare the timeout from the `IncreaseTimeout` and the expected timeout

Fixes: [#2958](https://github.com/openeverest/openeverest/issues/2958)

### CODE REVIEW

File: internal/server/session_failures_storage_test.go [hunk 1]
```diff
@@ -31,11 +32,13 @@ func TestRateLimiterMemoryStore_ConcurrentAllowAndIncreaseTimeout(t *testing.T)
 	})
 
 	const identifier = "1.2.3.4"
-	const iterations = 200
+	const iterations = 20
 
 	var wg sync.WaitGroup
 	wg.Add(2)
 
+	store.Allow(identifier)
```
Comment (recharte) [inline internal/server/session_failures_storage_test.go]: CI's `Check` job is red on this line:

```
internal/server/session_failures_storage_test.go:40:13: Error return value of `store.Allow` is not checked (errcheck)
```

Discard it explicitly, the way the goroutine just below already does.

Worth a line of *why* while you're in there. This call is the load-bearing half of the fix and it's the one thing here that looks removable — a bare call with a thrown-away result, sitting right next to a goroutine that calls `Allow` in a loop. Without a note, the next tidy-up deletes it and quietly restores exactly the no-op #2958 describes.

```suggestion
	// Register the visitor first: IncreaseTimeout silently returns when the
	// identifier has no visitor yet, so without this the writer goroutine can
	// drain every iteration without ever touching Visitor.timeout.
	_, _ = store.Allow(identifier)
```

File: internal/server/session_failures_storage_test.go [hunk 2]
```diff
@@ -51,4 +54,13 @@ func TestRateLimiterMemoryStore_ConcurrentAllowAndIncreaseTimeout(t *testing.T)
...
 	wg.Wait()
+
+	expectedTimeout := initialTimeout << iterations
+
+	store.mutex.Lock()
+	v, _ := store.visitors[identifier]
+	actualTimeout := v.timeout
+	store.mutex.Unlock()
+
+	assert.Equal(t, expectedTimeout, actualTimeout)
```
Comment (recharte) [inline internal/server/session_failures_storage_test.go]: The other half of the red `Check` job:

```
internal/server/session_failures_storage_test.go:61:2: S1005: unnecessary assignment to the blank identifier (staticcheck)
```

Just dropping the `, _` clears the lint but leaves the real problem: if the visitor ever isn't in the map, `v.timeout` panics instead of failing the test. Binding `ok` fixes both.

Two things in the rewrite that aren't obvious: the unlock moves *above* the assertions because a failing `require` calls `runtime.Goexit()`, which would leave `store.mutex` held for the rest of the run; and reading `v.timeout` unlocked is safe here because `wg.Wait()` has already joined both writers.

```suggestion
	store.mutex.Lock()
	v, ok := store.visitors[identifier]
	store.mutex.Unlock()

	require.True(t, ok, "visitor was removed during the run")
	assert.Equal(t, initialTimeout<<iterations, v.timeout)
```

This needs `"github.com/stretchr/testify/require"` alongside the `assert` import you added.

**Review by recharte — CHANGES_REQUESTED** [review]
Hey @Phran6ix, thanks for picking this one up — the assertion is exactly the half of #2958 that mattered, and it's right.

Two lint failures from the `Check` job inline, both one-liners; that's the only thing holding this up.

**Comment by Phran6ix** [comment]
Thank you for the review @recharte . I have made the requested changes.

File: internal/server/session_failures_storage_test.go [hunk 3]
```diff
@@ -51,4 +55,14 @@ func TestRateLimiterMemoryStore_ConcurrentAllowAndIncreaseTimeout(t *testing.T)
...
+
+	expectedTimeout := initialTimeout << iterations
+
+	store.mutex.Lock()
+	v, ok := store.visitors[identifier]
+	actualTimeout := v.timeout
+	store.mutex.Unlock()
+
+	require.True(t, ok, "Visitor was removed during the run")
+	assert.Equal(t, expectedTimeout, actualTimeout)
```
Comment (recharte) [inline internal/server/session_failures_storage_test.go]: `ok` is bound now, thanks — but the check ended up below the dereference it was meant to guard:

```go
v, ok := store.visitors[identifier]
actualTimeout := v.timeout                                 // nil deref here if !ok
store.mutex.Unlock()

require.True(t, ok, "Visitor was removed during the run")  // never reached
```

`v` is a `*Visitor`, so a missing key gives you nil and line 63 panics before line 66 ever runs — `require.True` can only fire in the case where it has nothing to do. Given what this PR is about, worth not shipping another guard that reads as a guard 🙂

Moving the read below the `require` means `v.timeout` is read outside the lock, which is safe here: `wg.Wait()` has already joined both writers, so there's no concurrent access left for `-race` to find.

```suggestion
	store.mutex.Lock()
	v, ok := store.visitors[identifier]
	store.mutex.Unlock()

	require.True(t, ok, "Visitor was removed during the run")
	assert.Equal(t, expectedTimeout, v.timeout)
```

File: internal/server/session_failures_storage_test.go [hunk 4]
```diff
@@ -31,11 +33,13 @@ func TestRateLimiterMemoryStore_ConcurrentAllowAndIncreaseTimeout(t *testing.T)
 	})
 
 	const identifier = "1.2.3.4"
-	const iterations = 200
+	const iterations = 20
 
 	var wg sync.WaitGroup
 	wg.Add(2)
 
+	_, _ = store.Allow(identifier)
```
Comment (recharte) [inline internal/server/session_failures_storage_test.go:44]: The errcheck half of this landed, thanks. The comment half didn't, and this is still the one line in the test that reads as safe to delete: a bare call with a discarded result, sitting directly above a goroutine that calls `Allow` in a loop. That's the exact shape of the thing #2958 is about.

```suggestion
	// Register the visitor first: IncreaseTimeout silently returns when the
	// identifier has no visitor yet, so without this the writer goroutine can
	// drain every iteration without ever touching Visitor.timeout.
	_, _ = store.Allow(identifier)
```

**Comment by Phran6ix** [comment]
Hello @recharte 

The tests are failing in the plugin subsystem which I did not touch.
could this be a known issue on main or what I am supposed to do?

**Comment by recharte** [comment]
> Hello @recharte
> 
> The tests are failing in the plugin subsystem which I did not touch. could this be a known issue on main or what I am supposed to do?

Yes, this was caused by PR that got merged incorrectly, it has been reverted. Please update your branch and it should be fixed.

File: internal/server/session_failures_storage_test.go (hunk 3 above)
Comment (Phran6ix) [reply internal/server/session_failures_storage_test.go]: Okay.  I understand now.
Thank you so much @recharte .

**Comment by Phran6ix** [comment]
Hello @recharte 

I have updated the pr, awaiting review

**Review by recharte — APPROVED** [review]
Thanks @Phran6ix

**Comment by Phran6ix** [comment]
Thank you so much for the help @recharte I really enjoyed working on this and i would like to continue contributing to the project. 
should I pick up another good first issue or are there particular areas of the codebase/project you'd recommend I look into?
